-- 创建预约表
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  appointment_date DATE NOT NULL,
  appointment_time TEXT NOT NULL,
  doctor TEXT NOT NULL,
  symptoms TEXT,
  status TEXT DEFAULT '待确认' CHECK (status IN ('待确认', '已确认', '已完成', '已取消'))
);

-- 创建RLS策略，允许所有用户插入数据
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

-- 允许匿名用户插入预约数据
CREATE POLICY "允许匿名用户插入预约" 
  ON appointments FOR INSERT 
  TO anon 
  WITH CHECK (true);

-- 允许已认证用户查看所有预约数据
CREATE POLICY "允许已认证用户查看所有预约" 
  ON appointments FOR SELECT 
  TO authenticated 
  USING (true);

-- 允许已认证用户更新预约状态
CREATE POLICY "允许已认证用户更新预约" 
  ON appointments FOR UPDATE 
  TO authenticated 
  USING (true);

-- 允许已认证用户删除预约
CREATE POLICY "允许已认证用户删除预约" 
  ON appointments FOR DELETE 
  TO authenticated 
  USING (true);